### PR TITLE
Add Excel generation 1

### PR DESCRIPTION
**Pull request by simonprast**
**Checklist:**

 
 - [x] Have you added an explanation of what your changes do and why you'd like them to be included?
 - [ ] Have you updated or added documentation for the change?
 - [x] Have you tested your changes with successful results?

**Type of Changes:**

 
 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [x] New feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change)

**What is the current behavior? (link to any open issues here)**
- The email field is not required anymore, but in the code it is listed under required fields (code quality). Issue #83 
- Beautyreport generation should support tab stops. Issue #88
- Excel generation when creating an Anamnese should be added. Issue #89

**What is the new behavior (if this is a feature change)?**
- The position of the email field is changed.
- ~Tab Stops in the beautyreport generation do not work fully at the moment, but a prototype is already implemented.~
- Tab Stops are added to the Beautyreport generation. Tab Stops can be accessed with `<tab>` in the Beautyreport template page. Tab Stops are default Word length.
- ~A first version of Excel generation is added. This uses the labels of the wagtail form fields as the keys. This will be changed. Also GraphQL queries must still be added.~
- Excel generation is added. The data is displayed with the field's help_text in the left columns and the Coach's answer in the right columns. Excel documents can be queried like Beautyreport documents.
  - To implement this, forms can now accept an alternative form of data:
      > A form can either be submitted as `'key': 'value'`, which is always valid. In this case, the following section will not be able to convert the form data and the program will continue as usual. Or the form is submitted as `'key': '{'helpText': helpText, 'fieldType': fieldType, 'value': value}'`. In this case, if the form can entirely be translated (each key has a value field in its dict), it is also a valid submission.
- An app is added which adds three additional Anamnese-like questionnaires which can be created in the Wagtail CMS as `Q1FormPage`, `Q2FormPage `and `Q3FormPage`. The questionnaires also support the new form submission format - even though no Excel sheets can be created yet and therefore the extra values are not used.

### CODE REVIEW

**Review by Aichnerc — APPROVED** [review]
Code quality okay.

**Review by Aichnerc — CHANGES_REQUESTED** [review]
Oh wait. Some of your commits are not verified. Please verify those commits.

**Comment by simonprast** [comment]
My commits are unverified as I do not have access to my Key's email address (<contact@simonprast.com>). They will be verified once I can receive mails again.

**Review by Aichnerc — CHANGES_REQUESTED** [review]
I do not approve this pull request due to its unverified commits.
However, due to an urgent request by @dermrsimon this pull request will be merged - with the promise, which I here perpetuate, to fix the unverified commits.

**Pull request merged**
